# Generated by Django 3.2.6 on 2024-12-30 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_receta_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='receta',
            old_name='difficulty',
            new_name='comensales',
        ),
        migrations.RenameField(
            model_name='receta',
            old_name='servings',
            new_name='dificultad',
        ),
        migrations.RenameField(
            model_name='receta',
            old_name='tags',
            new_name='etiquetas',
        ),
        migrations.RenameField(
            model_name='receta',
            old_name='ingredients',
            new_name='ingredientes',
        ),
        migrations.RenameField(
            model_name='receta',
            old_name='instructions',
            new_name='instrucciones',
        ),
        migrations.RenameField(
            model_name='receta',
            old_name='program',
            new_name='programa',
        ),
        migrations.RenameField(
            model_name='receta',
            old_name='author',
            new_name='tiempo',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='source_url',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='time',
        ),
        migrations.AddField(
            model_name='receta',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='home.autor'),
        ),
        migrations.AddField(
            model_name='receta',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='home.categoria'),
        ),
    ]
